version: '2'

services:
  redis:
      image: redis
      ports:
        - "6379:6379"
  mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: 123456
         MYSQL_DATABASE: spring_cloud
  kafka:
     image: spotify/kafka:0.10.1.1
     ports:
       - "2181:2181"
       - "9092:9092"
     environment:
        ADVERTISED_HOST: 127.0.0.1