version: "3"
services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test1
    volumes:
      - ./src/main/mysql:/etc/mysql/conf.d